name: publish npm
on: 
  push:
    tags:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        run: |
          echo '${{ secrets.TOKEN }}'>.npmrc
          npm publish --registry https://registry.npmjs.org